blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from core import views
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new_post/', views.new_post, )
    path('detail/<int:post_id>', views.post_detail, name='post_detail'),

]

core/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    author = models.CharField(max_length = 250, null = True)
    title = models.CharField(max_length = 250)
    post_text = models.TextField()
    is_active = models.BooleanField(default = True)
    published_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-published_on']

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    author_comment = models.CharField(max_length = 250, null=True)
    comment_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.created_at)

    class Meta:
        ordering = ['-created_at']

core/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    # comment_text = forms.CharField(widget = forms.Textarea(attrs={'rows':'3'}))
    class Meta:
        model = Comment
        fields = ['author_comment', 'comment_text']

core/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import CommentForm

# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {
        'posts':posts,
    }
    return render(request, 'core/index.html', context)

def post_detail(request, post_id):
    post = Post.objects.get(id = post_id)
    comments = post.comment_set.all()
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit = False)
            new_comment.post = post
            new_comment.save()
            form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }

    return render(request, 'core/detail.html', context)

core/templates/core/detail.html
{%extends 'base.html'%}
{% load static %}
{% block content %}
  <h1>{{post.title}}</h1>
  <hr>
  <h5 class="right">Published On: {{post.published_on | date:"d M Y"}} - {{post.published_on | time:"H:i"}}</h5>
  <div class="post_block">
    <p class="flow-text post_text">{{post.post_text}}</p>
    <br>
    <p class="right">Author: {{post.author}}</p>
    <br><br>
    <hr>
  </div>
  <div class="row">
    <div class="col s12 m11">
      <div class="card-panel">
        <span class="card-title">New Comment</span>
        <form class="" action="" method="post">
          {% csrf_token %}
          {{form.as_p}}
          <input class="btn" type="submit" name="" value="submit">
        </form>
      </div>
    </div>
  </div>
  <div class="">
    {% for comment in comments %}
      <p class="flow-text comment_text">{{comment.comment_text}}</p>
      <p class="">Created at: {{comment.created_at | date:"d M Y"}} - {{comment.created_at | time:"H:i"}} by <strong>{{comment.author_comment}}</strong></p>
      <hr>
    {% endfor %}
  </div>
{% endblock%}

core/templates/core/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>Posts</h1>
  {% for post in posts %}
    <div class="row">
      <div class="col s12 m10">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <a href="{% url 'core:post_detail' post.id %}"><span class="card-title">{{post.title}}</span></a>
            <p>{{post.post_text|truncatewords:50}}</p>
            </div>
            <div class="card-action">
              <a href="{% url 'core:post_detail' post.id %}"><i class="small material-icons">comment</i><span class="total_comment">{{post.comment_set.count}}</span></a>
            </div>
          </div>
        </div>
      </div>
  {% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Arcanus - Blog</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/materialize.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
      {% block content %}

      {% endblock %}
      <script type="text/javascript" src="{% static 'js/jquery-3.5.0.js'%}"></script>
      <script type="text/javascript" src="{% static 'js/materialize.js'%}"></script>
      <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    </div>
  </body>
</html>

templates/navbar.html
{% load static %}
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo"><img class="logo" src="{% static 'img/logo.png' %}" alt="Arcanus"></a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">About</a></li>
        <li><a href="badges.html">GitHub</a></li>
        <li><a href="#"><i class="material-icons">person</i></a></li>
      </ul>
    </div>
  </nav>
  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
  </ul>